version: 0.2

phasese:
   build:
     command:
        - echo Entered the build phase...
        - mvn clean package
      
   post_build:
     commands:
       - echo Build completed succesfulluy.
      
artifacts:
  files: 
   - target/connect-two-db.jar
  discard-paths: yes 
            