version: 0.2

phases:
  #install:
    #runtime-versions:
      #java: corretto8
  build:
    commands:
      - echo Build started on succesfully
      #- mvn test 
  post_build:
    commands:
      - echo Build completed on succesfully
      - mvn package
artifacts:
  files:
    - target/connect-two-db.jar
  discard-paths: yes